######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 24 19:50:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..

# Input
SOURCES += main.cpp \
    renderwindow.cpp \
    ../jpegdecoder.c \
    decoderthread.cpp

HEADERS += \
    renderwindow.h \
    ../jpegdecoder.h \
    decoderthread.h
